# File: _config.yml

# Configurazione dei plugin
plugins:
  - jekyll-relative-links

# Configurazione dei link relativi
relative_links:
  enabled: true
  collections: true

# File da includere
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
