#dopo @ il nome del branch stabile
remote_theme: "jekyll/minima@2.5-stable"

# Configurazione dei plugin
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

# Configurazione dei link relativi
relative_links:
  enabled: true
  collections: true

# File da includere
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
